### ISSUE TITLE
Logging Version Constraint

### ISSUE THREAD

**Issue by butlermatt** [dartist/redis_client#59]
Would it be feasible to broaden the logging package version constraint. Currently 0.1.15 depends on logging ^0.9.0, but our project depends on logging ^0.11.2.

Alternatively, is this package still active? Would it be better to fork it?

**Comment by mythz** [comment]
We've had a few maintainers in the past, but ultimately I think most have moved on - if you'd like I can give you contributor access?

**Comment by butlermatt** [comment]
@mythz Yeah I think this is a valuable and well established library (also listed as the 'preferred' library on the redis site) and would like to see it continued. I'd be happy to help collaborate with it as much as I can.

**Comment by mythz** [comment]
@butlermatt no worries, GitHub shouldv'e sent an invite request?

**Comment by butlermatt** [comment]
@mythz Yep done thanks. Will that enable me to upload to pub as well or still need someone else for that?

**Comment by mythz** [comment]
I'll need to add that too, just need to remember how. What email should I use?

**Comment by butlermatt** [comment]
butler.matthew@gmail.com

**Comment by mythz** [comment]
Got it thx, you should be added to the uploaders list now. Feel free to remove your email from public comment.

**Comment by butlermatt** [comment]
A follow up to this. I managed to get some time to get this updated, and was about to do a push to pub, but I notice the version of pub is actually a couple of versions ahead of the current version in here. Anyone know who pushed to pub last time and from what repo, I don't want to cause any regressions.
